// formidable/presets/vue/files/resources/js/Pages/Welcome.vue
<template>
  <div class="container">
    <div class="content">
      <div class="logo">
        <img src="/formidable.png" />
      </div>

      <div class="welcome">
        <h4>Yey! You have successfully created a new Formidable project.</h4>
      </div>

      <div class="information">
        Formidable v{{ formidableVersion ?? "undefined" }} (Node {{ nodeVersion ?? "undefined" }})
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    formidableVersion: String,
    nodeVersion: String,
  },
};
</script>

// formidable/presets/react/files/js/Pages/Welcome.jsx
export default function Welcome({ formidableVersion, nodeVersion }) {
	return (
		<div className="container">
			<div className="content">
				<div className="logo">
					<img src="/formidable.png" />
				</div>

				<div className="welcome">
					<h4>Yey! You have successfully created a new Formidable project.</h4>
				</div>

				<div className="information">
					Formidable v{ formidableVersion ?? "undefined"} (Node { nodeVersion ?? "undefined"})
				</div>
			</div>
		</div>
	)
}
